#!/usr/bin/env bash

dmh="[`date +%d-%m-%H`]"
logfile=/tmp/login.log
prazdniki=(1511 0101 0201 0301 0401 0501 0601 0701 0801 2302 2402 2502 0803 0903 1003 1103 2904 3004 0105 0205 0905 1006 1106 1206 0311 0411 0511 3012 3112)

if [[ `grep "admin.*$(echo $PAM_USER)" /etc/group` ]]
 then
   echo "$dmh $PAM_USER - you are welcome!" >> $logfile
   exit 0
elif [[ `grep "myusers.*$(echo $PAM_USER)" /etc/group` ]]
 then
   if [[ " `date +%u` " > " 5 " ]]
    then
     echo "$dmh $PAM_USER - weekend now!" >> $logfile
     exit 1
   elif [[ " ${prazdniki[@]} " =~ " `date +%d%m` " ]]
    then
     echo "$dmh $PAM_USER - is party day!" >> $logfile
     exit 1
   else
     echo "$dmh $PAM_USER - you may pass" >> $logfile
     exit 0
    fi
else
   echo "$dmh anohter user $1 shall pass" >> $logfile
   exit 0
fi