# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :'master.homework.local' => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  },
  :'node1.homework.local' => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151'
  },
  :'node2.homework.local' => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.152'
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end
          box.vm.provision "ansible" do |ansible|
            ansible.become = true
            ansible.verbose = "vv"
            ansible.playbook = "add_local_user.yml"
          end
      end
  end
end