# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:Router1 => {
      :box_name => "centos/7",
      :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "area0"},
                  {ip: '10.10.1.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "area1"}
              ]
  },
  :Router2 => {
    :box_name => "centos/7",
    :net => [
                {adapter: 2, auto_config: false, virtualbox__intnet: "area0"},
                {ip: '10.10.2.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "area2"},
                {ip: '172.16.16.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "area4"}
            ]
},
  :Router3 => {
      :box_name => "centos/7",
      :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "area0"},
                  {ip: '10.10.3.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "area3"}
              ]
  },
  :Client1 => {
    :box_name => "centos/7",
    :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "area1"}
            ]
},
  :Client2 => {
    :box_name => "centos/7",
    :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "area2"}
            ]
},
  :Client3 => {
    :box_name => "centos/7",
    :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "area3"}
            ]
},
  :Vault => {
    :box_name => "centos/7",
    :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "area4"}
            ]
}
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end
        box.vm.provision "ansible" do |ansible|
          ansible.become = true
          ansible.verbose = "v"
          ansible.playbook = "add_local_user.yml"
        end        
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL


        
        case boxname.to_s
          when "Router1"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              yum -y install quagga tcpdump
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
              echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=192.168.10.1\nPREFIX=30\nDEVICE=eth1.1" > /etc/sysconfig/network-scripts/ifcfg-eth1.1
              echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=192.168.10.10\nPREFIX=30\nDEVICE=eth1.3" > /etc/sysconfig/network-scripts/ifcfg-eth1.3
              systemctl restart network
              cp /vagrant/router1/zebra.conf /etc/quagga/zebra.conf
              cp /vagrant/router1/ospfd.conf /etc/quagga/ospfd.conf
              cp /vagrant/etc/hosts /etc/hosts
              cp /vagrant/etc/daemons /etc/daemons
              chown quagga:quaggavt /etc/quagga/ospfd.conf && chown quagga:quagga /etc/quagga/zebra.conf
              systemctl enable zebra ospfd && systemctl start zebra ospfd
              setsebool -P zebra_write_config 1
              SHELL
            # box.vm.provision "ansible" do |ansible|
            #   ansible.become = true
            #   ansible.verbose = "v"
            #   ansible.playbook = "network-nmcli.yml"
            # end
          when "Router2"
            # Router2 Hasicorp Vault interface
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              yum -y install quagga tcpdump
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
              echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=192.168.10.2\nPREFIX=30\nDEVICE=eth1.1" > /etc/sysconfig/network-scripts/ifcfg-eth1.1
              echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=192.168.10.5\nPREFIX=30\nDEVICE=eth1.2" > /etc/sysconfig/network-scripts/ifcfg-eth1.2
              systemctl restart network
              cp /vagrant/router2/zebra.conf /etc/quagga/zebra.conf
              cp /vagrant/router2/ospfd.conf /etc/quagga/ospfd.conf
              cp /vagrant/etc/hosts /etc/hosts
              cp /vagrant/etc/daemons /etc/daemons
              chown quagga:quaggavt /etc/quagga/ospfd.conf && chown quagga:quagga /etc/quagga/zebra.conf
              systemctl enable zebra ospfd && systemctl start zebra ospfd
              setsebool -P zebra_write_config 1
              SHELL
            # box.vm.provision "ansible" do |ansible|
            #   ansible.become = true
            #   ansible.verbose = "v"
            #   ansible.playbook = "network-nmcli.yml"
            # end
          when "Router3"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              yum -y install quagga tcpdump
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
              echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=192.168.10.6\nPREFIX=30\nDEVICE=eth1.2" > /etc/sysconfig/network-scripts/ifcfg-eth1.2
              echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=192.168.10.9\nPREFIX=30\nDEVICE=eth1.3" > /etc/sysconfig/network-scripts/ifcfg-eth1.3
              systemctl restart network
              cp /vagrant/router3/zebra.conf /etc/quagga/zebra.conf
              cp /vagrant/router3/ospfd.conf /etc/quagga/ospfd.conf
              cp /vagrant/etc/hosts /etc/hosts
              cp /vagrant/etc/daemons /etc/daemons
              chown quagga:quaggavt /etc/quagga/ospfd.conf && chown quagga:quagga /etc/quagga/zebra.conf
              systemctl enable zebra ospfd && systemctl start zebra ospfd
              setsebool -P zebra_write_config 1
              SHELL
            # box.vm.provision "ansible" do |ansible|
            #   ansible.become = true
            #   ansible.verbose = "v"
            #   ansible.playbook = "network-nmcli.yml"
            # end
          when "Vault"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            yum install -y epel-release
            yum install -y openvpn easy-rsa
            #  && yum update -y unzip wget && yum update -y
            # wget https://releases.hashicorp.com/vault/1.0.2/vault_1.0.2_linux_amd64.zip
            # unzip vault_1.0.2_linux_amd64.zip
            # mv ./vault /usr/bin
            # mkdir -p /etc/vault && mkdir -p /var/lib/vault
            # adduser usemod chown
            # cp /vagrant/vault/config.json /etc/vault
            # cp /vagrant/vault/vault.service /etc/systemd/system && systemctl enable vault && systemctl start vault
            # echo -e "export VAULT_ADDR=http://192.168.10.14:8200" >> ~/.bashrc
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=172.16.16.10\nPREFIX=24\nGATEWAY=172.16.16.1\nDEVICE=eth1" > /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            cp /vagrant/ca/vars /usr/share/easy-rsa/3.0.3/easyrsa/
            cd /etc/openvpn/server
            # build server key
            /usr/share/easy-rsa/3.0.3/easyrsa init-pki
            /usr/share/easy-rsa/3.0.3/easyrsa build-ca nopass
            /usr/share/easy-rsa/3.0.3/easyrsa gen-dh
            /usr/share/easy-rsa/3.0.3/easyrsa build-server-full server nopass
            cp /vagrant/secret/static.key /etc/openvpn/server/static.key
            # build client config
            /usr/share/easy-rsa/3.0.3/easyrsa build-client-full client nopass
            cp /vagrant/ca/client.tmpl /etc/openvpn/server/client.tmpl
            cp /vagrant/ca/5in1 /etc/openvpn/server/common && chmod +x ./common && ./common
            cp /vagrant/ca/server.conf /etc/openvpn/server/server.conf
            mkdir -p /etc/openvpn/server/ccd
            cp ./client.conf /vagrant/ca/client.conf
            systemctl enable openvpn-server@server.service && systemctl start openvpn-server@server
            # cp /vagrant/ca/server.conf /etc/openvpn/server/server.conf
            # /usr/share/easy-rsa/3.0.3
            SHELL
            box.vm.provision "ansible" do |ansible|
              ansible.become = true
              ansible.verbose = "v"
              ansible.playbook = "fetch.yml"
            end
          when "Client1"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            yum install -y epel-release
            yum install -y openvpn easy-rsa wget
            echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=10.10.1.2\nPREFIX=24\nGATEWAY=10.10.1.1\nDEVICE=eth1" > /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            cp /vagrant/etc/hosts /etc/hosts
            #
            # OpenVPN server tun
            #
            # cp /vagrant/tun/server.conf /etc/openvpn/server/server.conf
            # cp /vagrant/secret/static.key /etc/openvpn/server/static.key
            # systemctl enable openvpn-server@server.service && systemctl start openvpn-server@server
            #
            # OpenVPN server tap
            #
            cp /vagrant/tap/server.conf /etc/openvpn/server/server.conf
            cp /vagrant/secret/static.key /etc/openvpn/server/static.key
            systemctl enable openvpn-server@server.service && systemctl start openvpn-server@server
            # vault
            wget https://github.com/Luzifer/vault-openvpn/releases/download/v1.8.0/vault-openvpn_linux_amd64.tar.gz && \
            tar -zxvf vault-openvpn_linux_amd64.tar.gz 
            #
            #
            SHELL
          when "Client2"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            yum install -y epel-release
            yum install -y openvpn easy-rsa
            echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=10.10.2.2\nPREFIX=24\nGATEWAY=10.10.2.1\nDEVICE=eth1" > /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            cp /vagrant/etc/hosts /etc/hosts
            #
            # OpenVPN client tun
            #
            # cp /vagrant/tun/server.conf /etc/openvpn/server/server.conf
            # cp /vagrant/secret/static.key /etc/openvpn/server/static.key
            # systemctl enable openvpn-server@server.service && systemctl start openvpn-server@server
            #
            # OpenVPN client tap
            #
            cp /vagrant/tap/server.conf /etc/openvpn/server/server.conf
            cp /vagrant/secret/static.key /etc/openvpn/server/static.key
            systemctl enable openvpn-server@server.service && systemctl start openvpn-server@server
            #
            #
            SHELL
          when "Client3"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            yum install -y epel-release
            yum install -y openvpn easy-rsa
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=10.10.3.2\nPREFIX=24\nGATEWAY=10.10.3.1\nDEVICE=eth1" > /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            cp /vagrant/etc/hosts /etc/hosts
            #
            # OpenVPN client tun
            #
            # cp /vagrant/tun/client.conf /etc/openvpn/client/client.conf
            # cp /vagrant/secret/static.key /etc/openvpn/client/static.key
            # systemctl enable openvpn-client@client.service && systemctl start openvpn-client@client
            #
            # OpenVPN client tap
            #
            cp /vagrant/ca/client.conf /etc/openvpn/client/client.conf
            cp /vagrant/secret/static.key /etc/openvpn/client/static.key
            systemctl enable openvpn-client@client.service && systemctl start openvpn-client@client
            #
            # OpenVPN client tap
            #
            SHELL
          end
      end

  end
  
  
end
