# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
      :box_name => "centos/7",
      # :public => {:ip => '172.16.1.101', :adapter => 1},
      # :public => {adapter: 1, auto_config: true},
      :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"}
              ]
  },
:centralRouter => {
      :box_name => "centos/7",
      :net => [
                  {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                  {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "central-net"},
                  {ip: '192.168.1.1', adapter: 4, netmask: "255.255.255.128", virtualbox__intnet: "office2-net"},
                  {ip: '192.168.2.1', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office1-net"},
                  {adapter: 6, auto_config: false, virtualbox__intnet: "router-net"}
              ]
},
:centralServer => {
      :box_name => "centos/7",
      :net => [
                  {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "central-net"}
              ]
},
:office1Server => {
      :box_name => "centos/7",
      :net => [
                  {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office1-net"}
                ]
},
:office2Server => {
      :box_name => "centos/7",
      :net => [
                  {ip: '192.168.1.130', adapter: 2, netmask: '255.255.255.192', virtualbox__intnet: "office2-net"}
              ]
  },
:testServer1 => {
      :box_name => "centos/7",
      :net => [
        {adapter: 2, auto_config: false, virtualbox__intnet: "central-test"}
              ]
  },
:testServer2 => {
      :box_name => "centos/7",
      :net => [
        {adapter: 2, auto_config: false, virtualbox__intnet: "central-test"}
              ]
  },
:testClient1 => {
      :box_name => "centos/7",
      :net => [
        {adapter: 2, auto_config: false, virtualbox__intnet: "central-test"}
              ]
  },
:testClient2 => {
      :box_name => "centos/7",
      :net => [
        {adapter: 2, auto_config: false, virtualbox__intnet: "central-test"}
              ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end
        box.vm.provision "ansible" do |ansible|
          ansible.become = true
          ansible.verbose = "v"
          ansible.playbook = "add_local_user.yml"
        end        
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            # start bonding
            echo -e 'NM_CONTROLED=no\nDEVICE=bond0\nONBOOT=yes\nTYPE=Bond\nBONDING_MASTER=yes\nIPADDR=192.168.255.1\nPREFIX=30\nBOOTPROTO=static\nBONDING_OPTS="mode=1 miimon=100 fail_over_mac=1"' > /etc/sysconfig/network-scripts/ifcfg-bond0
            echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nONBOOT=yes\nDEVICE=eth1\nMASTER=bond0\nSLAVE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
            echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nONBOOT=yes\nDEVICE=eth2\nMASTER=bond0\nSLAVE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth2
            systemctl restart network
            # end bonding
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
            ip route add 192.168.0.0/16 via 192.168.255.2
            SHELL
        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
            echo "net.ipv4.conf.all.forwarding=1"  >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            echo -e 'NM_CONTROLED=no\nDEVICE=bond0\nONBOOT=yes\nTYPE=Bond\nBONDING_MASTER=yes\nIPADDR=192.168.255.2\nPREFIX=30\nGATEWAY=192.168.255.1\nBOOTPROTO=static\nBONDING_OPTS="mode=1 miimon=100 fail_over_mac=1"' > /etc/sysconfig/network-scripts/ifcfg-bond0
            echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nONBOOT=yes\nDEVICE=eth1\nMASTER=bond0\nSLAVE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth1
            echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nONBOOT=yes\nDEVICE=eth5\nMASTER=bond0\nSLAVE=yes" > /etc/sysconfig/network-scripts/ifcfg-eth5
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            # echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            # ip ro add default via 192.168.255.1 dev eth1 metric 1
            # Central office
            echo -e "BOOTPROTO=static\nONBOOT=yes\nIPADDR=192.168.0.33\nNETMASK=255.255.255.240\nDEVICE=eth2:0" > /etc/sysconfig/network-scripts/ifcfg-eth2:0
            echo -e "BOOTPROTO=static\nONBOOT=yes\nIPADDR=192.168.0.65\nNETMASK=255.255.255.192\nDEVICE=eth2:1" > /etc/sysconfig/network-scripts/ifcfg-eth2:1
            # Office 2      
            echo -e "BOOTPROTO=static\nONBOOT=yes\nIPADDR=192.168.1.129\nNETMASK=255.255.255.192\nDEVICE=eth3:0" > /etc/sysconfig/network-scripts/ifcfg-eth3:0
            echo -e "BOOTPROTO=static\nONBOOT=yes\nIPADDR=192.168.1.193\nNETMASK=255.255.255.192\nDEVICE=eth3:1" > /etc/sysconfig/network-scripts/ifcfg-eth3:1
            # Office 1
            echo -e "BOOTPROTO=static\nONBOOT=yes\nIPADDR=192.168.2.65\nNETMASK=255.255.255.192\nDEVICE=eth4:0" > /etc/sysconfig/network-scripts/ifcfg-eth4:0
            echo -e "BOOTPROTO=static\nONBOOT=yes\nIPADDR=192.168.2.129\nNETMASK=255.255.255.192\nDEVICE=eth4:1" > /etc/sysconfig/network-scripts/ifcfg-eth4:1
            echo -e "BOOTPROTO=static\nONBOOT=yes\nIPADDR=192.168.2.193\nNETMASK=255.255.255.192\nDEVICE=eth4:2" > /etc/sysconfig/network-scripts/ifcfg-eth4:2
            systemctl restart network
            SHELL
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip ro add default via 192.168.0.1 dev eth1 metric 1
            # echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            # echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            # systemctl restart network
            SHELL
        when "office1Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip ro add default via 192.168.2.1 dev eth1 metric 1
            # echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            # echo "GATEWAY=192.168.2.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            # sudo systemctl restart network
            SHELL
        when "office2Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            # nmcli con modify "System eth0" ipv4.gateway "0.0.0.0"
            # nmcli c mod "System eth0" ipv4.never-default false
            # nmcli con modify "System eth1" ipv4.gateway "192.168.1.129"
            # nmcli con reload "System eth0"
            # nmcli com reload "System eth1"
            echo "GATEWAY=192.168.1.129" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl stop NetworkManager
            systemctl disable NetworkManager
            sleep 5
            systemctl restart network
            # nmcli connection reload
            # ip ro del default via 10.0.2.2 dev eth0 proto dhcp metric 100
            # nmcli dev re eth0
            # nmcli dev re eth1
            # ip ro add default via 192.168.1.129 dev eth1 metric 1
            SHELL
          # box.vm.provision "ansible" do |ansible|
          #   ansible.become = true
          #   ansible.verbose = "v"
          #   ansible.playbook = "network-nmcli.yml"
          # end
        when "testServer1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=10.10.10.1\nNETMASK=255.255.255.0\nDEVICE=eth1.1" > /etc/sysconfig/network-scripts/ifcfg-eth1.1
            # cat /some_path/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
            # sudo systemctl restart network
            SHELL
        when "testServer2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=10.10.10.1\nNETMASK=255.255.255.0\nDEVICE=eth1.2" > /etc/sysconfig/network-scripts/ifcfg-eth1.2
            # sudo systemctl restart network
            SHELL
        when "testClient1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=10.10.10.254\nNETMASK=255.255.255.0\nDEVICE=eth1.1" > /etc/sysconfig/network-scripts/ifcfg-eth1.1
            # cp -a ./some_path/id_rsa /home/vagrant/.ssh/
            # sudo systemctl restart network
            SHELL
        when "testClient2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
          echo -e "NM_CONTROLED=no\nBOOTPROTO=static\nVLAN=yes\nONBOOT=yes\nIPADDR=10.10.10.254\nNETMASK=255.255.255.0\nDEVICE=eth1.2" > /etc/sysconfig/network-scripts/ifcfg-eth1.2
          # sudo systemctl restart network
            SHELL
          end
      end

  end
  
  
end
